### PR TITLE
root-imp-inputs

### PR DESCRIPTION
**Pull request by nicitaacom**
# Changes
1. Root page fixed
2. secondary - changed as in figma
opacity 0.4 changed to 0.75
3. Ckeckbox added
4. Radio button added
5. Usage example added
6 .Button.tsx improved

**Notion task** - https://www.notion.so/39d5f132e6dd483ea6a128c7152f5009?v=159487785be744a39ac2478076bbe410&p=56cb1f7756824238b006d71d6d75a61d&pm=s
This task done - delete this branch and move task in notion to 'Done'

### CODE REVIEW

**Review by arifm6 — CHANGES_REQUESTED** [review]
# Requested Changes_1

1. The changes break all 3 of the authentication pages (signin, signup, recover-account). Here is an example of how the new signup page looks: 
image. Can you clean up the unused elements so it looks similar to what it was before and I will make it as it is in figma. Here is an example of some unnecessary elements in the current code: 
Screenshot 2023-08-04 at 11 09 20 AM
 
2. The checkbox hover still does not always work as expected. If you hover over the "remember me" checkbox on the signin or signup pages, the green hover box does not work as expected and is not centered with the checkbox. It is hard to take a screenshot because it is a hover effect but it is easy to reproduce by simply hovering over the "remember me" checkbox. I also noticed you used the css ::before property property found here: 
Screenshot 2023-08-04 at 11 01 49 AM I would suggest instead of this, create an empty absolute div in the JSX of the checkbox component and work with that instead as it is more predictable and easy to work with. However, you can do it whichever way you prefer but I find it easier to use an empty div instead.
3. If you would like to add an id prop so that each input can have a unique id and each label can have a unique htmlFor attribute, that would help with accessibility and form submission. I noticed in some components you do have an id such as here: 
image
however, if you are making multiple checkboxes on one page, then they will all have the same id which is not good. The way you did it in the RadioButton component is good so if you could change the Input and Checkbox component to be like that, it would be better. 
4. On the Input component you have no label but it would be good practice for accessibility to make a label (and include an htmlFor) for every input. You can hide the label if you dont want it to appear on screen.

Overall it looks much better and easier to maintain.

**Comment by nicitaacom** [comment]
# Reply to requested changes_1

 ### 1. About deleting unnecessary components
 I did it to you understand that now it works and you can get value
 Anyway you can check out the docs in src/components/ui/dev_readme.md
 I clean up it today and send you new pull request to review
 
 ### 2. We don't use JSX - we use .tsx
 (jsx - its javascript with jsx return statement and tsx - its TypeScript with return statement)
 By tsx or jsx return statement I mean this
image
I wrote it to you undestand it much clear and so - we will have no misscommunicate
Also it would be nice if you do a recording of the problem (you may use OBS for it)

### 3. I don't understand what do you mean by 'accessibility' 
3.1. acessibility to what to input?
3.2 how it can be used?
3.3 how it help for form submission (by submission you mean submit?)
3.4 
> 'if you are making multiple checkboxes on one page, then they will all have the same id which is not good''

why its not good?
Ok I add it to Checkbox.tsx and Input.tsx today (05.08.2023)

### 4. We already have label in Input.tsx
image
Why do we need htmlFor?
> You can hide the label if you dont want it to appear on screen.

What? - more details please (about what label you wrote adbout how you see it in your head? - now label in Input.tsx instad placeholder to make it as in figma UX effect (all UX we comment in figma)

Thank you for pull request review
Please add more details and context next time (like why its good what do you mean by something)
Also please add number of requested changes - so we will understand what requested changes you reply to
And add spaces between points 1 2 3 - because now it looks like 1 whole change
Check notion I updated basic rules - https://www.notion.so/Basic-rules-06942f8ecb6f4139ba8191cb6c02238dg

**Review by arifm6 — CHANGES_REQUESTED** [review]
# Requested Changes_2

 ### 1. Accessibility and htmlFor improvement
Previously, you asked what I mean by accessibility. In terms of web development, accessibility refers to the practice of making websites available to all users, including those with disabilities. Imagine there was a blind person who listens to a screen reader to know what is on a page. The visual label that you have may not be useful but the htmlFor helps the screen reader associate each label with its corresponding input. This will make it easier for the blind person to know what that input is for because it helps his device read it easier. In general, it is good practice to include an htmlFor for all labels because it will help users with assistive technology. Refer to the screenshot at the end for both changes 1. and 2.


### 2. Multiple id's on the same page 
You also asked me why it is not good for multiple checkboxes on one page to have the same id. In HTML, each element can have only one id. Each id on a page, can only be used for 1 element unlike classes that can be reused. The id attribute is used to uniquely identify each element. If you have 3 elements that have the same id="check" (as you do in the checkbox component), it defeats the purpose of using an id because now, there is no way to uniquely identify them by id. Using something such as Document.getElementById... is useless now because there are multiple elements on the same page with the same id. 

image
This is an example of a good RadioButton input component. Even though the htmlFor helps with interacting with the component on screen, it also helps screen readers. Additionally, the id is dynamic because you put id={label} and not id="radio" or something like that. This way, you won't have multiple elements with the same id on page. These are minor things but if you do the other two inputs like you did for RadioButton.tsx, it would be better.

Overall, the changes you implemented fixed the major issues and it looks really good. I think there may be some language/communication barrier but it helps when you ask me to clarify. I think one thing major thing is that you prefer images and videos whereas I like to be descriptive with text. I think with the language barrier I will try to use more images but if there is any room for improvement, let me know.

**Comment by nicitaacom** [comment]
Thank you for pull request review

# Reply to requested changes_2
> ### 1. Accessibility and htmlFor improvement
I don't think that blind person will visit our site because is anybody else who cares about this blind person can visit our site and choose bag for blind person needs - if you know that its best practice - ok I add htmlFor for label and id for input
> ### 2. Multiple id's on the same page
I don't remember that I asked you about 
> why it is not good for multiple checkboxes on one page to have the same id

Please add quote next time (you you want know how style markdonw click here)
image
Also please specify number of requested changes what i reply to (e.g Requested changes_1)
>  because now, there is no way to uniquely identify them by id

Why you need it - I mean for what reason you waht add id - what it will used for? - answer to unique each element tell me nothing - provide example please - like you add id here and you can become this result (for example by clicking on label you input field get focus state) 
>  such as Document.getElementById...

Please don't use document... in React - use useRef for it - if you need get acces to ref in another component use zustnad for it

I added id for RadioButton in reason because - without it it doesn't work (not for document.querySelector or screen reader for blind users)

I don't have problems with understanding english language - somethimes I have problems with understanding what do you mean - please clarify next time what do you mean and it would be good if you provide some examples (I don't prefer do something without understanding why I'm doing this - and I'm sure that answer 'it's the best practice' its really bad reason to do something - I'm really really believe that you need do some mistake and understand that (in our case) its bad to keep Input.tsx without id - so I will don't add it only its reason of 'best practice' - provide 1 or 2 examples why its bad (reason about blind person its so-so because we haven't any statistic how much users use screen reader and we have good design so you can understand what something mean even without see what exactly on your screen) - if you really sure and want defend your position we always can discuss it in discord (if it takes more 5 min to read your position)

About images and videos its obviosely because so you can provide more context without lorem1000 - so you save my time
I find something like (now it like this 'image' - do it like this 'image' will give you more context than if you describe it throught text)

**Comment by nicitaacom** [comment]
# Changes_1
 1. Readme refactired and dev_readme improved

 2. Added styles for 'Forgot password'

 3. 'Forgot password' removed from signUp.tsx

 4. Input w-full

 5. Usage example deleted

 6. Input.tsx placeholder required

 7. Checkbox hover effect centered

 8. Button.tsx - variant nav-link  - added space 2px between line and label

 9. SignInForm.tsx adn SignUpForm.tsx added `<Button/>` instead native `<button/>`

 10. SignUpForm added `<Button variant='link'/>` instead of native `<button/>`

Please next time apply tailwind styles as in figma

**Comment by nicitaacom** [comment]
# Changes_2
Nothing because in my oppiniton no reason to add id and htmlFor for Input.tsx (becasue we haven't any case with blind user and in my oppninos is anybody who can help buy bag for blind user)

Please specify next time what exactly changes you want from me (specify it in title) (e.g add id for label and input in Input.tsx)

**Review by arifm6 — DISMISSED** [review]
# Comments

Changes approved as the requested changes were minor and not worth disagreeing over.

**Review by arifm6 — APPROVED** [review]

**Pull request merged**
