### PR TITLE
products-fix-imagesSize

### PR DESCRIPTION
**Pull request by ottakist**
issue resolved

### CODE REVIEW

**Comment by ottakist** [comment]
can change alignment to this:
image
or leave it as it already is:
image

**Comment by nicitaacom** [comment]
Leave this
image

**Comment by nicitaacom** [comment]
Only I have this issue that I don't see bg-img?
image

**Comment by nicitaacom** [comment]
image
image

**Comment by nicitaacom** [comment]
Also improve alignment now - to don't create new branch for it

**Comment by ottakist** [comment]
not sure what you meant by those drawings. But placing "price" to the top looks like shit
image

**Comment by ottakist** [comment]
for now, I'll leave the price as it was before. If you have a different opinion please provide at least a draft layout of what you've meant

**Comment by ottakist** [comment]
By the way, I think it looks good when you have at least some text in description
image

**Comment by ottakist** [comment]
> Only I have this issue that I don't see bg-img? image

And yes. Only you have this issue cause the project is optimized poorly. And your internet speed is not enough to load bg and images at the same time

**Comment by nicitaacom** [comment]
> not sure what you meant by those drawings. But placing "price" to the top looks like shit image

Absolutely (cause font doesn't fit)

**Comment by nicitaacom** [comment]
> for now, I'll leave the price as it was before. If you have a different opinion please provide at least a draft layout of what you've meant

Yes - I also think so (that better draw it in figma first)

**Comment by nicitaacom** [comment]
> > Only I have this issue that I don't see bg-img? image
> 
> And yes. Only you have this issue cause the project is optimized poorly. And your internet speed is not enough to load bg and images at the same time

I waited to much and I made relocation that's why internet should be fine (I could load 720p YouTube video when I was checking it)
1 more review required to check only I have this but or no - I request Ahmad to to this

**Comment by nicitaacom** [comment]
image
Today everything is fine with bg-img

**Review by nicitaacom — APPROVED** [review]
Looks fine

**Pull request merged**
