### PR TITLE
home-imp-responsive

### PR DESCRIPTION
**Pull request by nicitaacom**
# Changes
### 1. Improved responsive design
Added desktop media-query
Minor fixes in tsconfig - deleted 1 line because unused

**Notion task** - https://www.notion.so/39d5f132e6dd483ea6a128c7152f5009?v=159487785be744a39ac2478076bbe410&p=560116d341424b9ebb20070b96f75920&pm=s
This task done - delete this branch and move task in notion to 'Done'

### CODE REVIEW

**Review by arifm6 — CHANGES_REQUESTED** [review]
# Requested changes_1
### 1. Fix responsiveness for mobile.

The home page responsiveness has some issues on mobile screen sizes and on low screen heights. Here is an example:  
Screenshot 2023-08-23 at 11 34 45 PM
image
It seems that the height of your carousel is the same regardless of your screens height which may be causing this issue.
### 2. tailwind config mobile size adjusted
I noticed you changed the tailwind config mobile width to 415px. Is there a reason for this? Minimum widths are usually around 320.

**Comment by nicitaacom** [comment]
Thank you for pull request review

# Reply to requested changes_1
> ### 1. Fix responsiveness for mobile.
Thank you that you mentioned about it
> ### 2. tailwind config mobile size adjusted
> I noticed you changed the tailwind config mobile width to 415px. Is there a reason for this? 

The best practices its don't change something - just add (in rarely cases may change name of variable or function but not value of some variable or logic of some function)
I just added mobile and desktop breackpoints
You're right minimum width === 320

**Comment by nicitaacom** [comment]
# Changes_2
### 1.  Fix responsiveness for mobile
Of course it looks not in the best way on 443x580 but its no screens with such width and height
image

**Review by arifm6 — APPROVED** [review]
ideally fix the text cutting off on odd breakpoints but it looks better overall.

**Pull request merged**
