### PR TITLE
cart-fix-buttonLayout

### PR DESCRIPTION
**Pull request by ottakist**
# Changes
### 1. Fixed buttons layout on "Cart" page

**Notion task** - https://www.notion.so/cart-fix-buttonLayout-63c4a640cfa648af89f26fd8b5843367
This task done - delete this branch and move task in notion to 'Done'

### CODE REVIEW

**Review by nicitaacom — CHANGES_REQUESTED** [review]
Thank you that you use snippet for pull request provided in Notion
I believe that you will use it in feature - you really help me to keep it clean


# Requested changes_2
<details>
<summary>1. Match it with figma design</summary>
Now it looks like so

image
</details>




<details>
<summary>2. Fix this layout bug</summary>

image

</details>

**Comment by ottakist** [comment]
> 

I cannot see the bug you mentioned. Please let me know if it still exists.

**Comment by nicitaacom** [comment]
# Requested changes_3

### 1. Match it with figma design</summary>

image

Add gap-y between 'Clear cart' and 'Submit'

**Comment by ottakist** [comment]
can you be more specific about the design you want me to change? Because I don't consider what happens in Figma to be proper "design".  I redesign things that look poor on the page to improve their appearance.  If there are any essential things in "design" you would like implemented, please highlight them so we can discuss or implement them.

**Review by nicitaacom — APPROVED** [review]
Match it with figma design next time - so you save my and your time
If you want do changes to design across 'products' 'product' 'cart' - feed free - its your space

**Pull request merged**
