### PR TITLE
implemented root layout component

### PR DESCRIPTION
**Pull request by arifm6**

### CODE REVIEW

**Review by nicitaacom — CHANGES_REQUESTED** [review]
image
You broke something
Please every time before making pull request - make sure that everything is fine and you didn't broke smth

**Comment by nicitaacom** [comment]
I made some changes so - make git pull
And also everytime check is you up to date with development and have you something to pull or no
And remember every time add new version - its important for development branch when we decide go back - so we will understand what version was

**Comment by arifm6** [comment]
> image You broke something Please every time before making pull request - make sure that everything is fine and you didn't broke smth

I looked into it and it looks like the previous version had an "overflow-hidden" applied to the entire wrapping div which resulted in one of the children staying within the contents viewport and not creating that white space. It would be better if we did not use css properties like that because then it makes debugging difficult later. The issue appears to be in the Slider component and i would suggest fixing that instead of relying on an overflow:hidden applied to the wrapping div of every page.

**Comment by nicitaacom** [comment]
> > image You broke something Please every time before making pull request - make sure that everything is fine and you didn't broke smth
> 
> I looked into it and it looks like the previous version had an "overflow-hidden" applied to the entire wrapping div which resulted in one of the children staying within the contents viewport and not creating that white space. It would be better if we did not use css properties like that because then it makes debugging difficult later. The issue appears to be in the Slider component and i would suggest fixing that instead of relying on an overflow:hidden applied to the wrapping div of every page.

I had to make smth like this
image
And I think that overflow:hidden solves some problems when some element outside <body>
About css something inpossible to write with tailwind that's why I use css (and I from start suggested use css for components)

**Comment by nicitaacom** [comment]
Try fix it how you want
I check it and give you my feedback

**Review by nicitaacom — CHANGES_REQUESTED** [review]
Please bro before creating new pull request - test - have you broken something or no
image

**Review by nicitaacom — APPROVED** [review]
Yes - well done - I like it

**Pull request merged**
