### PR TITLE
root-imp-navbar

### PR DESCRIPTION
**Pull request by nicitaacom**
# Changes
1. Navbar for desktops and mobiles
2. Hover for nav-links
3. Animations for navbar

**Notion task** - https://www.notion.so/39d5f132e6dd483ea6a128c7152f5009?v=159487785be744a39ac2478076bbe410&p=bc9287c1c4094b73a1d04d0022eafca4&pm=s
This task done - delete this branch and move task in notion to 'Done'

### CODE REVIEW

**Comment by ottakist** [comment]
Well. on mobile animation looks ok, but the alignment is not great. 
image
maybe it would be better to make it buttons with the same width and then align them. I can't make up propper style yet, but kinda in this way:
image

**Comment by ottakist** [comment]
And this just looks really bad
image
Maybe it's a bug but it still need to be fixed
image
Nav buttons need to be placed on the right side. And the buttons are kinda small on big screen

**Review by ottakist — CHANGES_REQUESTED** [review]
Well. on mobile animation looks ok, but the alignment is not great. 
image
maybe it would be better to make it buttons with the same width and then align them. I can't make up propper style yet, but kinda in this way:
image
What I provided also looks like shit, so we need to make design improvements there

And this just looks really bad
image
Maybe it's a bug but it still needs to be fixed
image
Nav buttons need to be placed on the right side. And the buttons are kinda small on the big screen

**Comment by nicitaacom** [comment]
text-xs
image
text-md
image

This the best one - text-sm
image

**Comment by nicitaacom** [comment]
About alignment - on my side it looks normal
image

If it possible draw it with lightshot - otherwise draw it in figma how you see it in your head

**Review by ottakist — APPROVED** [review]
On desktop version now looks great. In my opinion, the mobile design is currently lacking. However, I am unsure of how to improve it at the moment. Therefore, I suggest we leave it as is for now.

**Comment by nicitaacom** [comment]
> On desktop version now looks great. In my opinion, the mobile design is currently lacking. However, I am unsure of how to improve it at the moment. Therefore, I suggest we leave it as is for now.

Move it to 'Done' in Notion

**Pull request merged**
