### PR TITLE
23.06.2023 products page

### PR DESCRIPTION
**Pull request by ottakist**
Data values are hardcoded

### CODE REVIEW

**Comment by nicitaacom** [comment]
Make merge from development to your this branch

**Comment by nicitaacom** [comment]
Its great that you created pull request (show me how you did it and I show Ahmad how do it) - better show us how create pull request

I also want know what changes you did - so it would be nice when you explain me everything in discord (DM me about it)

**Comment by nicitaacom** [comment]
Also we have unresolved problem with tailwind.config.ts - bg-bg-primary - its not good idea to use

**Comment by ottakist** [comment]
> Also we have unresolved problem with tailwind.config.ts - bg-bg-primary - its not good idea to use

this issue occurred because I had "bg-bg-primary" across the project and so it works. 
You can see that there is no unresolved problem in this pull request 
image
So it means that you need to merge files in order of provided pull request

**Comment by ottakist** [comment]
at this point, i can't change my pull request

**Comment by ottakist** [comment]
> Its great that you created pull request (show me how you did it and I show Ahmad how do it) - better show us how create pull request
> 
> I also want know what changes you did - so it would be nice when you explain me everything in discord (DM me about it)

I also haven't done any changes to existing code or logic. I've just created a page for Products and components accordingly.
you can review the files in pull request and I can answer your question if you'll have any

**Comment by nicitaacom** [comment]
> > Its great that you created pull request (show me how you did it and I show Ahmad how do it) - better show us how create pull request
> > I also want know what changes you did - so it would be nice when you explain me everything in discord (DM me about it)
> 
> I also haven't done any changes to existing code or logic. I've just created a page for Products and components accordingly. you can review the files in pull request and I can answer your question if you'll have any

First question:
Have you did merger from development to your branch?
(I did a couple of merges to development branch today - so I relly want make sure that you up to date)
Send me please picture which confirms that you up to date with development branch

**Review by nicitaacom — CHANGES_REQUESTED** [review]
As I can see you not up do date with development branch because changes in BAKCEND (we haven't this changes in development)

Please do merge from development to your branch and resolve all conflicts (like bg-bg-primary)

We have antoher tailwind.config.js that's why will be conflicts

**Comment by ottakist** [comment]
sure i'm not updated at this point 
but i was when I pushed it 4 hours ago, and you pushed hour ago without first accepting this pull request - that is where conflict appeared 
image

**Comment by ottakist** [comment]
next time if you see someone made pull request first review it and then make new changes cause you kinda screwed your own logic

**Comment by ottakist** [comment]
At this point you even accepted Ahmad changes which rewrites the whole directory. That means I can't resolve problem between files and merge them together since I have basically different folder structure - I don't know how to fix this except copypaste files manually

**Comment by ottakist** [comment]
i still can do this but that wasn't nice. Please try to avoid these situations

**Comment by ottakist** [comment]
once again no error
image
please perform review before implementing new logic

**Comment by nicitaacom** [comment]
You are checkung unresolved conversations
Conversations in this context have no relation to actuall code conflicts
You should have something like suggestion to resolve conflicts in vs code (it should be green and red in vs code)

I suggest call you 25.06.2023 at 10:00 and resolve it - how you find it?

**Comment by nicitaacom** [comment]
> 

I merge that branch to development because no issues was there
Here I see issue that folders are still separeted
And as I asid before for example Ahmad can finish his task first (that's why you need do merge from development to your branch and resolve all confilicts)

**Comment by nicitaacom** [comment]
> At this point you even accepted Ahmad changes which rewrites the whole directory. That means I can't resolve problem between files and merge them together since I have basically different folder structure - I don't know how to fix this except copypaste files manually

I don't know exactly how it in 'git graph' or 'git bash' but in 'github desktop' you would have new changes and you old changes and you need move files from driectory FRONTEND to root dicectory and that resolves conflict
(yes also can be conflicts like so - I mean withour overwriting file - when you just have another folder structure)

**Comment by nicitaacom** [comment]
> i still can do this but that wasn't nice. Please try to avoid these situations

Avoid situations when we change folder structure?
If you mean so if even depends not only on me - Ahmad said that will better - I like why - he explain me that T3 App have FullStack support and we don't need do it - I just - ok and he unseparate folders

If you want you can DM me in discord and I help you resolve this conflict
I need somehow make sure that after merging to development we willn't have FRONTEND and BACKEND folders

**Comment by nicitaacom** [comment]
I reviewed changes and can't understand why you have added tsconfig.json when it already exists
Now I understand that you want merge your branch to 'production' branch - please create pull request for merging it to the 'development' branch
image

**Pull request closed without merging**
