### PR TITLE
products-imp-listViewLayout

### PR DESCRIPTION
**Pull request by ottakist**
Notion task: https://www.notion.so/products-imp-listViewLayout-e685673d15ea43b0a480e022d1234df0

### CODE REVIEW

**Comment by nicitaacom** [comment]
Please send me next time notion-link which relates to this task

Also it would be nice when you will write smth like this - it helps me understand what exatly you did
# Changes
1. 
2. 
3. 



**Notion task** _(on review)_ - 
This task done - delete this branch and move task in notion to 'Done'

If you want you can use this
image
So it will faster

**Review by nicitaacom — CHANGES_REQUESTED** [review]
Create:
3 cols for HD+
2 cols for tablet+
1 cols default
image

by cols I mean className='grid grid-cols-1 tablet:giod-cols-2 laptop:grid-cols-3'

Improve design using  /components/ui/Button.tsx
I did pull request - check it first

Also next time send me that I noticed in notion (so we will have all requested changes in 1 place because it can be in github and in notion and I find it not good)
For this go to notion - basic rules (on left sidebar) - second point

**Review by nicitaacom — CHANGES_REQUESTED** [review]
Price formater - https://www.notion.so/39d5f132e6dd483ea6a128c7152f5009?v=159487785be744a39ac2478076bbe410&p=b008d52445194c1cab4f8590f1101946&pm=s
Decrease scale on hover - https://www.notion.so/39d5f132e6dd483ea6a128c7152f5009?v=159487785be744a39ac2478076bbe410&p=c53bec81fbed43a7a4864a09e1f1c96c&pm=s

image
It should shave the same width (50%) - do it as in figma (don't apply any additional classes for Button.tsx
image

**Comment by ottakist** [comment]
> It should shave the same width (50%) - do it as in figma (don't apply any additional classes for Button.tsx 
image

What "It" should have the same width (50%)? 50% of what? 
Is that ok?
image

**Comment by ottakist** [comment]
oh, maybe you meant buttons?

**Comment by ottakist** [comment]
now there is following issue with priceFormatter
image
image

**Comment by ottakist** [comment]
Possible solutions:
1:70/30
image
2:get rid of word "Buy"
image

**Comment by ottakist** [comment]
Details for this task awaited 
https://www.notion.so/39d5f132e6dd483ea6a128c7152f5009?v=159487785be744a39ac2478076bbe410&p=c53bec81fbed43a7a4864a09e1f1c96c&pm=s

**Comment by nicitaacom** [comment]
> Possible solutions: 1:70/30 image 2:get rid of word "Buy" image

I see third solution
This 320px right?
Create unique media-query for this
image
And calculate approximatly when this bug will not exist
image

**Comment by nicitaacom** [comment]
I mean for normal view with 2 buttons (50%) each it requires width - calculate how much width it requires to avoid this text-wrap
it should be smth like this
className='max-[400px]:flex-col'

**Comment by ottakist** [comment]
> I mean for normal view with 2 buttons (50%) each it requires width - calculate how much width it requires to avoid this text-wrap it should be smth like this className='max-[400px]:flex-col'

Do you mean if there is to match text that causes wrap it should look like this:
image
and when there is no issue it should look like this?
image

**Comment by ottakist** [comment]
or just make this for the mobile version?
image

**Comment by nicitaacom** [comment]
> > I mean for normal view with 2 buttons (50%) each it requires width - calculate how much width it requires to avoid this text-wrap it should be smth like this className='max-[400px]:flex-col'
> 
> Do you mean if there is to match text that causes wrap it should look like this: image and when there is no issue it should look like this? image


About this - yes you'r right
image

**Comment by nicitaacom** [comment]
About this
image

With button label 'Buy $1099.99'

**Comment by ottakist** [comment]
Oh, I see but. O don't like this idea cause there will basically be two different styles for the same component. In that case, I suggest using this style for all items 
image

**Comment by nicitaacom** [comment]
> Oh, I see but. O don't like this idea cause there will basically be two different styles for the same component. In that case, I suggest using this style for all items image

I didn't get you
What 2 different styles you writing about?

**Comment by ottakist** [comment]
I'll just do these buttons for the mobile version
image

**Comment by nicitaacom** [comment]
> I'll just do these buttons for the mobile version image

Let me know when you done

**Review by nicitaacom — CHANGES_REQUESTED** [review]
# Changes 1
In figma it so (button label is 'Buy $199.99')
image

Now it so (Without 'Buy')
image

# Changes 2
image

#Changes 3
Should be 1 scrollbar (custom scrollbar)
image

**Comment by nicitaacom** [comment]
Did you run 'pnpm lint'?
If no - run it

**Comment by ottakist** [comment]
when you change screen size using dev tools - update the page cause it should look like this 
on desktop:
image
and for mobile:
image
If you see smth different update page first

**Comment by nicitaacom** [comment]
It looks bad on Tablet (I refreshed page)
image

Also I have question why its not change design immediately when I shrink screen in dev tools? (why I need reload page?)

**Review by nicitaacom — CHANGES_REQUESTED** [review]
Fix view on Tablet (768x1024)

**Comment by ottakist** [comment]
> Fix view on Tablet (768x1024)

Do you mean image shrink?

**Comment by ottakist** [comment]
It doesn't transform immediately, cause there is not much option to make conditional rendering in the tailwind. I chose this approach cause users don't use dev tools, obviously. the only way, you'd notice it is by changing screen size

**Comment by ottakist** [comment]
image
This issue seems to be occurred by the default behavior of Next.js Image or provided aspect ratio of the images. I don't know how to deal with either of those.
Maybe you or Ahmad would know what styles should be applied here:
image

**Comment by ottakist** [comment]
I used this approach:
image
works fine but over the rules, I guess.
image

**Comment by ottakist** [comment]
And there are some issues with the images you've provided. Some of them have the main content on the left or right and others on the center. so I can't provide the same alignment for all elements.

**Pull request merged**
