### PR TITLE
home-add-UX4ctaText

### PR DESCRIPTION
**Pull request by nicitaacom**
Possible 3 different animations - I 'peeked' (chose) the best one

### CODE REVIEW

**Comment by nicitaacom** [comment]
# Changes
1. Animation on hover on cta text on / added



**Notion task** - https://www.notion.so/39d5f132e6dd483ea6a128c7152f5009?v=159487785be744a39ac2478076bbe410&p=9358f9ab6aaa44b9b1992cedf9d204e2&pm=s
This task done - delete this branch and move task in notion to 'Done'

**Review by ottakist — CHANGES_REQUESTED** [review]
My name is "Illia". Overall ok. Will approve it as soon as you fix it.

**Comment by nicitaacom** [comment]
Illia I change it - thank you that you noticed about it - I will know

**Comment by nicitaacom** [comment]
Also I want review from Ahmad is everythig is fine - don't merge it

**Review by ottakist — DISMISSED** [review]

**Review by arifm6 — DISMISSED** [review]

**Review by arifm6 — APPROVED** [review]

**Comment by nicitaacom** [comment]
@arifm6 
image
Please delete branch next time if it requires

**Pull request merged**
